name: Dev to Staging Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PAC CLI manually
      run: |
        Invoke-WebRequest -Uri "https://github.com/microsoft/powerplatform-cli/releases/download/v1.45.3/pac-win-x64.zip" -OutFile "pac.zip"
        Expand-Archive -Path "pac.zip" -DestinationPath "$env:USERPROFILE\tools\pac"
        echo "$env:USERPROFILE\tools\pac" | Out-File -FilePath $env:GITHUB_PATH -Append
      shell: pwsh

    - name: Authenticate to Dev
      run: |
        pac auth clear
        pac auth create `
          --applicationId "${{ secrets.CLIENT_ID }}" `
          --clientSecret "${{ secrets.CLIENT_SECRET }}" `
          --tenant "${{ secrets.TENANT_ID }}" `
          --environment "${{ secrets.DEV_ENV_URL }}"
      shell: pwsh

    - name: Export solution from Dev
      run: |
        pac solution export `
          --name D365LightQuotingSystem `
          --path exported/D365LightQuotingSystem.zip `
          --managed false `
          --environment "${{ secrets.DEV_ENV_URL }}"
      shell: pwsh

    - name: Authenticate to Staging
      run: |
        pac auth clear
        pac auth create `
          --applicationId "${{ secrets.CLIENT_ID }}" `
          --clientSecret "${{ secrets.CLIENT_SECRET }}" `
          --tenant "${{ secrets.TENANT_ID }}" `
          --environment "${{ secrets.STAGING_ENV_URL }}"
      shell: pwsh

    - name: Import solution to Staging
      run: |
        pac solution import `
          --path exported/D365LightQuotingSystem.zip `
          --environment "${{ secrets.STAGING_ENV_URL }}" `
          --force-overwrite `
          --publish-changes
      shell: pwsh
