name: Export Power Platform Solution from Dev

on:
  workflow_dispatch:

jobs:
  export-solution:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Power Platform CLI via Winget
      shell: powershell
      run: |
        winget install --id Microsoft.PowerApps.CLI -e --accept-package-agreements --accept-source-agreements

    - name: Authenticate to Dev
      shell: powershell
      run: |
        $clientId = "${{ secrets.CLIENT_ID }}"
        $clientSecret = "${{ secrets.CLIENT_SECRET }}"
        $tenantId = "${{ secrets.TENANT_ID }}"
        $envUrl = "${{ secrets.DEV_ENV_URL }}"
        pac auth create `
          --url $envUrl `
          --clientId $clientId `
          --clientSecret $clientSecret `
          --tenant $tenantId `
          --kind AAD

    - name: Export solution from Dev
      shell: powershell
      run: |
        pac solution export `
          --name D365LightQuotingSystem `
          --outputFile solution.zip `
          --managed false `
          --overwrite
